version: "3"
services:
  NodeEstudo:
    image: node:latest
    container_name: NodeEstudo
    working_dir: /app
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./:/app
    tty: true
